# preload = /home/derek/Pictures/bg/fractal1/Apo7X-Super-Phoenix.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/Apo7X-Super-Phoenix.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/Apo7X-Super-Phoenix.png

wallpaper {
    # monitor = HDMI-A-1
    monitor =
    # path = ~/Pictures/bg/fractal1/
    path = ~/Pictures/bg/fractal1/Flame_2024-09-27-152504_3.png
    fit_mode = cover
    # order = random
    # timeout = 1800
}

# wallpaper {
#     monitor = HDMI-A-2
#     path = ~/Pictures/bg/fractal1/
#     fit_mode = cover
#     # order = random
#     timeout = 1741
# }

# To switch wallpapers, uncomment the one you want and comment out the current one:
# preload = /home/derek/Pictures/bg/fractal1/200226-10-4k-blk.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/200226-10-4k-blk.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/200226-10-4k-blk.png

# preload = /home/derek/Pictures/bg/fractal1/90s.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/90s.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/90s.png

# preload = /home/derek/Pictures/bg/fractal1/Apophysis-200310-108-4k-blk.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/Apophysis-200310-108-4k-blk.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/Apophysis-200310-108-4k-blk.png

# preload = /home/derek/Pictures/bg/fractal1/atomic-plum.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/atomic-plum.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/atomic-plum.png

# preload = /home/derek/Pictures/bg/fractal1/bg.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/bg.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/bg.png

# preload = /home/derek/Pictures/bg/fractal1/bg2.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/bg2.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/bg2.png

# preload = /home/derek/Pictures/bg/fractal1/cyberpunk-sloth.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/cyberpunk-sloth.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/cyberpunk-sloth.png

# preload = /home/derek/Pictures/bg/fractal1/cyberpunk-city.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/cyberpunk-city.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/cyberpunk-city.png

# preload = /home/derek/Pictures/bg/fractal1/digital-torpor.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/digital-torpor.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/digital-torpor.png

# preload = /home/derek/Pictures/bg/fractal1/fractal-cool-9001.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/fractal-cool-9001.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/fractal-cool-9001.png

# preload = /home/derek/Pictures/bg/fractal1/genesis.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/genesis.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/genesis.png

# preload = /home/derek/Pictures/bg/fractal1/luminous.png
# wallpaper = HDMI-A-1,/home/derek/Pictures/bg/fractal1/luminous.png
# wallpaper = HDMI-A-2,/home/derek/Pictures/bg/fractal1/luminous.png
